coordinator:
  url: "http://coordinator.decus.io/api/"
ethclient:
  wss_url: wss://kovan.infura.io/ws/v3/
btcesplora:
  url: https://blockstream.info/testnet/api/
contract:
  decus_system: "0xeC32A7d1DA03681D2CeC6fCFaE7Bc62d3F78A8c8"
  keeper_registry: "0x9b2C37e10146577494c63224C1Eba0A9aC28D238"
