btc:
  network: testnet
  confirmations: 6
url:
  rpc: https://data-seed-prebsc-1-s1.binance.org:8545/
  coordinator: https://coordinator.decus.online/api/
  btcesplora: https://blockstream.info/testnet/api/
contract:
  decux_system: "0x2D387355e7Fd91581131676F9294AFF71Ca2A4c2"
  keeper_registry: "0xEA2422125F850D08c6C3017a13885eB69D16A791"
  decux_system_start_block: 28687259