btc:
  network: testnet
  confirmations: 6
url:
  coordinator: http://127.0.0.1:5000/api/
  btcesplora: https://blockstream.info/testnet/api/
contract:
  decus_system: "0x58CE570B940BdB9597a6399A15AB3eE6634B59Eb"
  keeper_registry: "0x5b7ea705a49e70dbc749323d41C1ac3e35703827"
  decus_system_start_block: 11546136
