btc:
  network: testnet
url:
  coordinator: http://coordinator.decus.io/api/
  ethclient: wss://kovan.infura.io/ws/v3/
  btcesplora: https://blockstream.info/testnet/api/
contract:
  decus_system: "0x367Dc8B13Ca07F301122B436D204E2c52B76025C"
  keeper_registry: "0x5e77B65E9b78d66056C7048C773C81327bc79Fd6"
